### ISSUE TITLE
Does deleted file space recovered?

### ISSUE THREAD

**Issue by hrchu** [ibm-research/LTFS-Data-Management#11]
Hi I am curious about how LTFS-DM overcome tape block free up issue. Does LTFS-DM recover deleted file space?

**Comment by martin-petermann** [comment]
Hi,

what do you mean by "tape block free up issue"? Do you refer to the fact that tape is a serial media and data is only appended?

LTFS-DM currently does not recover a deleted file space. It is planned to add this functionality in future.

Thanks for looking at LTFS-DM.

**Comment by hrchu** [comment]
Got it, thanks for the project!
